[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.71.0",
    "biopython>=1.85",
    "openai>=2.6.0",
    "pandas>=2.3.3",
    "streamlit>=1.50.0",
]
